image:
  file: Dockerfile.gitpod
tasks:
  - command: >
      pg_start.sh &&
      bundle install &&
      RACK_ENV=gitpod bundle exec rake db:create &&
      RACK_ENV=gitpod bundle exec rake db:migrate