image:
  file: Dockerfile.gitpod
tasks:
  - init:
      bundle install --path vendor/bundle
    command:
      RACK_ENV=gitpod &&
      bundle exec rake db:create &&
      bundle exec rake db:migrate
