image:
  file: Dockerfile.gitpod
tasks:
  - before:
      pg_start.sh && createuser -s postgres
    init:
      bundle install
    command:
      bundle exec rake db:create &&
      bundle exec rake db:migrate
