image:
  file: Dockerfile.gitpod
tasks:
  - init:
      bundle install &&
      RACK_ENV=gitpod bundle exec rake db:create &&
      RACK_ENV=gitpod bundle exec rake db:migrate
    command: >
      pg_start.sh