language: ruby
rvm:
- 2.5.3
before_install:
- openssl aes-256-cbc -K $encrypted_6fd7155e1d69_key -iv $encrypted_6fd7155e1d69_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
- gem install bundle
- sudo apt update
- sudo apt -y install libsodium-dev
before_script:
- psql -c 'create database yuela_test;' -U postgres
- bundle exec rake db:migrate
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --debug"
dist: xenial
services:
- postgresql
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
- ssh-add -L
- ssh-keyscan atlas.hostineer.com > ~/.ssh/known_hosts
- ssh -vvvv cereal#grep.sh@atlas.hostineer.com
- git remote add deploy cereal#grep.sh@atlas.hostineer.com:repos/YuelaBot.git
- git push deploy HEAD:master
