language: ruby
cache: bundler
rvm:
- 2.5.3
before_install:
- openssl aes-256-cbc -K $encrypted_6fd7155e1d69_key -iv $encrypted_6fd7155e1d69_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
- gem install bundle
- sudo apt-get update
- sudo apt-get -y install libsodium-dev
before_script:
- psql -c 'create database yuela_test;' -U postgres
- RACK_ENV=test bundle exec rake db:migrate
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
dist: xenial
services:
- postgresql
deploy:
  provider: script
  script: rvm use 2.5.3 do bundle exec rake deploy
  skip_cleanup: true
  on:
    branch: master