language: ruby
cache: bundler
rvm:
- 2.5.3
env:
  - discord=FAKE_DISCORD_TOKEN
before_install:
- gem install bundler -v '2.0.2'
- sudo apt-get update
- sudo apt-get -y install libsodium-dev
- "curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl"
- "chmod +x ./kubectl"
- "sudo mv ./kubectl /usr/local/bin/kubectl"
- "sudo snap install doctl"
- "sudo snap connect doctl:kube-config"
- "doctl kubernetes cluster kubeconfig save $KUBERNETES_CLUSTER"
before_script:
- psql -c 'create database yuela_test;' -U postgres
- RACK_ENV=test bundle exec rake db:migrate
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t horizonshadow/yuelabot .
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
dist: xenial
services:
- postgresql
- docker
deploy:
  provider: script
  script: docker push horizonshadow/yuelabot && kubectl rollout restart deployment/yuelabot
  skip_cleanup: true
  on:
    branch: master