language: ruby
rvm:
- 2.5.3
before_install:
- openssl aes-256-cbc -K $encrypted_5d3af34cb5fc_key -iv $encrypted_5d3af34cb5fc_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
- ssh-add .travis/deploy_key
- gem install bundle
- sudo apt update
- sudo apt -y install libsodium-dev
before_script:
- psql -c 'create database yuela_test;' -U postgres
- bundle exec rake db:migrate
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --debug"
dist: xenial
services:
- postgresql
