language: ruby
rvm:
  - 2.5.3
before_install:
  - gem install bundle
  - sudo apt update
  - sudo apt -y install libsodium-dev
before_script:
  - psql -c 'create database yuela_test;' -U postgres
dist: xenial
services:
  - postgresql