version: '3.7'
services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 32768:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: yuela_dev
  yuela:
    build: .
    command: bundle exec ruby main.rb
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db
    environment:
      - RACK_ENV=docker-compose
volumes:
  postgres:
