development:
  adapter: postgresql
  host: db
  user: postgres
  password: postgres
  database: yuela_dev
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: postgres.main.yuelabot
  pool: 15
  timeout: 5000