gitpod:
  adapter: postgresql
  user: gitpod
  host: localhost
  database: yuela_dev
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  user: postgres
  host: localhost
  password: postgres
  database: yuela_dev
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  url: <%= ENV['YUELA_DATABASE_URL'] %>
  pool: 15
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  database: yuela_test
  user: postgres
  pool: 5
  timeout: 5000

docker-compose:
  adapter: postgresql
  host: db
  database: yuela_dev
  user: postgres
  pool: 5
  timeout: 5000